### ISSUE TITLE
How can i rectify this error related to curl when using brew ?

### ISSUE THREAD

**Issue by nmohanan** [virtphp/virtphp#67]
Error: Configure failed:
The last 5 lines in the log file:
checking whether to enable ctype functions... yes

checking for cURL support... yes

checking for cURL in default path... not found

configure: error: Please reinstall the libcurl distribution -

    easy.h should be in <curl-dir>/include/curl/

Please checkout the build log file for more details:

**Comment by ramsey** [comment]
It sounds like your question is related to either [Homebrew](https://github.com/Homebrew/brew/) or [PHPBrew](https://github.com/phpbrew/phpbrew). Depending on the tool you’re using, I recommend you ask one of those projects. Cheers!
